name: Compress and Upload to S3 on Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: ソースコードの圧縮
        run: |
          zip -r e2e-testing-code.zip ./ -x '*cdk*' '*doc*' '*node_modules*' '*.git*' '*.md'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/api-e2e-testing-githubactions-role
          aws-region: ap-northeast-1
      - name: S3にアップロード
        run: |
          aws s3 cp e2e-testing-code.zip s3://${{ vars.S3_BUCKET_NAME }}/e2e-testing-code.zip
